[project]
name = "demo"
version = "0.1.0"
description = "A litestar demo API"
readme = "README.md"

requires-python = ">=3.13,<4.0"

dependencies = [
    "litestar[jwt,pydantic,sqlalchemy,standard,structlog] (>=2.15.1,<3.0.0)",
    "asyncpg (>=0.30,<1.0)",
]
