services:
  demo-dev:
    container_name: demodev
    build:
      context: ..
      dockerfile: .devcontainer/backend/containerfile
    volumes:
      - ..:/demo
    command: sleep infinity
    networks:
      - demo
    depends_on: demodb

  demodb:
    container_name: demodb
    image: postgres:latest
    restart: unless-stopped
    volumes:
      # mount persistant volume for db data
      - demodb:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: demo
      POSTGRES_DB: demo
      POSTGRES_PASSWORD: demo
    ports:
      - 5432:5432
    networks:
      - demo

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.1.4
    restart: unless-stopped
    # volumes:
    #   - ./config/keycloak/:/opt/keycloak/data/import
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: demo
      KC_HEALTH_ENABLED: "true"
    command: start-dev #--import-realm
    ports:
      - 8080:8080
    networks:
      - demo
    healthcheck:
      # leverage some linux esoterica to call and parse the health api
      # https://stackoverflow.com/a/78229437
      test: [
        "CMD-SHELL",
        ' exec 3<>/dev/tcp/localhost/9000;
          echo -e "GET /health/ready HTTP/1.1\nhost: localhost:9000\n" >&3;
          timeout --preserve-status 1 cat <&3 | grep --max-count=1 status | grep --max-count=1 UP;
          ERROR=$?;
          exec 3<&-;
          exec 3>&-;
          exit $ERROR
        '
      ]
      interval: 5s
      timeout: 5s
      retries: 3

networks:
  demo:
    name: demo

volumes:
  # persistent volume for postgres data
  demodb:
    name: demodb
